spring.application.name=tms-web
spring.profiles.active=local


# Permite que o Spring entenda o SSL e o proxy reverso do Render
server.forward-headers-strategy=framework
server.tomcat.remoteip.remote-ip-header=x-forwarded-for
server.tomcat.remoteip.protocol-header=x-forwarded-proto
server.tomcat.remoteip.internal-proxies=.*

# Desativa Push e força Long Polling
vaadin.pushMode=disabled

# Configuração do Banco PostgreSQL Externo (Neon)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-plain-salad-ay4w521f-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_7oZcSOt0mfsn}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false

# Limite para upload de arquivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Porta dinâmica do Render
server.port=${PORT:10000}

spring.main.allow-bean-definition-overriding=true