spring.application.name=tms-web

# Permite que o Spring entenda o SSL e o proxy reverso do Render
server.forward-headers-strategy=framework
server.tomcat.remoteip.remote-ip-header=x-forwarded-for
server.tomcat.remoteip.protocol-header=x-forwarded-proto
server.tomcat.remoteip.internal-proxies=.*

# Desativa Push e força Long Polling
vaadin.pushMode=disabled

# Configuração do Banco PostgreSQL (Dados Persistentes)
spring.datasource.url=jdbc:postgresql://<HOSTNAME_DO_RENDER>:5432/dpg-da63v96k1f9s738v74gg-a
spring.datasource.username=tmsuser
spring.datasource.password=PhFrOrvtf7dgIH2aSIInzcrN011QdltG
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Limite para upload de arquivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Porta dinâmica do Render
server.port=${PORT:8082}