spring.application.name=tms-web

# Permite que o Spring entenda o SSL e o proxy reverso do Render
server.forward-headers-strategy=framework
server.tomcat.remoteip.remote-ip-header=x-forwarded-for
server.tomcat.remoteip.protocol-header=x-forwarded-proto

# Configuração do Banco H2 (Em Memória)
spring.datasource.url=jdbc:h2:mem:tmsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Limite para upload de arquivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Porta dinâmica do Render
server.port=${PORT:8082}

# Console H2
spring.h2.console.enabled=true